### ISSUE TITLE
Incorrect shutting down of bot

### ISSUE THREAD

**Issue by davfsa** [nekokatt/hikari#101]
### Steps to reproduce
1. Successfuly connect a bot to Discord
2. Disconnect it by causing a `KeyboardInterrupt`
3. Look at the Discord profile for the bot

### Expected Result
Bot goes offline

### Actual Result
Bot shows the last status before it shutdown

### System info
hikari v2.0.0 HEAD
located at /home/davfsa/coding/test-bots/hikari
CPython 3.8.2 GCC 9.3.0
Linux carbono 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64

### Further info
None

### Checklist

- [x] I have made sure to remove ANY sensitive information (bot token, passwords,
      credentials, personal details, etc).
- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by nekokatt** [comment]
This is a Discord bug.

**Comment by davfsa** [comment]
I added this as an issue since this used to work like this in the past and making a bot with other libs like discord.py. I thought this might be an issue when shutting down the bot

**Comment by nekokatt** [comment]
Nothing is documented on how to prevent this

**Comment by davfsa** [comment]
This does look like a bug on our side since we close the same way all other libs do (closing with code 1000) and taking into a consideration that other libs seem to work fine, im going to re-open this
