### ISSUE TITLE
Flatten `api` package into root package.

### ISSUE THREAD

**Issue by nekokatt** [nekokatt/hikari#104]
Flatten the `api` package into the root package.

- [ ] Move `api` to `hikari`.
- [ ] Ensure docstrings are updated
- [ ] Ensure tests are updated and pass
- [ ] Ensure MyPy passes.

**Comment by davfsa** [comment]
Wont this create too much of a mess in the root directory?

**Comment by nekokatt** [comment]
> Wont this create too much of a mess in the root directory?

Maybe. I'd like to have a discussion about this though as I don't feel like it is overly clear having half the API in a separate place right now.

We'd probably do well to consolidate some models together for models while we do this. For example, I see little benefit in presences being in it's own package right now.

**Comment by davfsa** [comment]
Ok, ig this one is liked a bit to #49 too
