### ISSUE TITLE
Consider implementing TRACE logging

### ISSUE THREAD

**Issue by nekokatt** [nekokatt/hikari#131]
Seems we can implement custom logger levels on the logging API, although not advised.

We may benefit from implementing a TRACE level for writing debugging payloads, preventing payload spam from DEBUG logs.

**Comment by davfsa** [comment]
Making our own logger level is as simple as logging at a specific int. DEBUG logs at int 10, so we might want to use `5`. This might also mean we should create our own loggers so we can do this `logger.trace(...)`. This function should be as the other logging ones, if the logger is not enabled for TRACE, don't do anything

**Comment by nekokatt** [comment]
@davfsa theres stuff for this already but it isn't advised and it is a silly idea so it is gone.
