### ISSUE TITLE
Implement crossposting related endpoints

### ISSUE THREAD

**Issue by FasterSpeeding** [nekokatt/hikari#135]
### Summary
https://github.com/discord/discord-api-docs/commit/960a8eaf13a55453e9a5aeafb1086645906d25ec

### Problem
Missing documented REST api coverage

### Ideal implementation
TBD

### Checklist

- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
Closed as of #147
