### ISSUE TITLE
DM channel lookup by ID

### ISSUE THREAD

**Issue by FasterSpeeding** [nekokatt/hikari#166]
### Summary
implement DM channel lookup by ID

### Problem
This should aid places such as PrivateMessageDeleteEvent.channel where we only have the DM channel's ID without a user

### Ideal implementation
TBD

### Checklist

- [x ] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by nekokatt** [comment]
If we could find out if channel IDs are always unique from user IDs, we could literally just store both in the same mapping as a hack.

I know Discord does this for some stuff.

**Comment by FasterSpeeding** [comment]
This is no-longer required as DMs will not be cached on a v8 gateway cache due to the lack of DM channel create events.
