### ISSUE TITLE
Migrate to TravisCI.com

### ISSUE THREAD

**Issue by nekokatt** [nekokatt/hikari#189]
We must migrate from TravisCI.org to TravisCI.com before 31st December 2020.

**Comment by FasterSpeeding** [comment]
Why?

**Comment by nekokatt** [comment]
> Why
TravisCI.org is being decommissioned (just if anyone else wanted to know that).

**Comment by nekokatt** [comment]
https://github.com/nekokatt/hikari/runs/1122814042

Looks like this is done.
