### ISSUE TITLE
Add logging for when chunking completes

### ISSUE THREAD

**Issue by nekokatt** [nekokatt/hikari#192]
We currently get this in debug logs:
```
D 2020-09-16 12:08:41,107 hikari.gateway.0: requesting guild members for guild 265828729970753537
```
...but then no indicator of when it completes, which is a little confusing as you don't know if it just jammed or not.

**Comment by davfsa** [comment]
That debug line could get removed, mostly because we don't track requested guild members, unless its from the `stateful_guild_chunker`. Will modify this to make it clear :+1:
