### ISSUE TITLE
Allow `ratelimit_per_user` to be a timedelta

### ISSUE THREAD

**Issue by davfsa** [nekokatt/hikari#207]
Another thought, wouldn't it make sense to also accept timedeltas for fields like this (especially as that's how we should be storing time deltas on models)?

_Originally posted by @FasterSpeeding in https://github.com/nekokatt/hikari/pull/203#discussion_r491698130_

**Comment by FasterSpeeding** [comment]
This should be closed

**Comment by nekokatt** [comment]
@FasterSpeeding why?

**Comment by FasterSpeeding** [comment]
> @FasterSpeeding why?

Oh wait, not yet. Sry stuff is just going by so fast rn and it's just like a whirl and I thought that pr had been merged already
