### ISSUE TITLE
Late binding of enumeration values.

### ISSUE THREAD

**Issue by nekokatt** [nekokatt/hikari#208]
I am proposing implementing late-binding of enumeration values in the same way some flags are.

This means storing integral values specifically on models as integers UNTIL they are needed by the user. They can then be transformed and restored as the enumeration type as and when first used.

This removes the majority of the overhead for parsing enums, as most enums won't ever be needed and thus will not be converted immediately; at the same time, no additional major overhead will occur, as the rebinding will only occur the first time it is used.

For example:

Before:
```py
@attr.s(eq=True, hash=True, init=True, kw_only=True, slots=True, weakref_slot=False)
class OwnGuild(guilds.PartialGuild):
    """Represents a user bound partial guild object."""

    is_owner: bool = attr.ib(eq=False, hash=False, repr=True)
    """`builtins.True` when the current user owns this guild."""

    my_permissions: permissions_.Permissions = attr.ib(eq=False, hash=False, repr=False)
    """The guild level permissions for this user."""
```

After:
```py
@attr.s(eq=True, hash=True, init=True, kw_only=True, slots=True, weakref_slot=False)
class OwnGuild(guilds.PartialGuild):
    """Represents a user bound partial guild object."""

    is_owner: bool = attr.ib(eq=False, hash=False, repr=True)
    """`builtins.True` when the current user owns this guild."""

    _my_permissions: int = attr.ib(eq=False, hash=False, repr=False)

    @property
    def my_permissions(self) -> permissions_.Permissions:
        """Return the guild-level permissions that apply to the current user.

        Returns
        -------
        hikari.permissions.Permissions
            The permissions in the guild.
        """
        # Enum lookups are very slow due to Python's implementation, and most
        # of the time, the conversion is not needed. Therefore, we delegate the
        # conversion to being performed the first time it is needed, and then
        # the internal value is simply updated for future use, so only the first
        # read carries significant overhead. This is basically a cached property
        # without an extra field being needed.
        if not isinstance(self._my_permissions, permissions_.Permissions):
            # This is unbound, we can convert it.
            self._my_permissions = permissions_.Permissions(self._my_permissions)
        return self._my_permissions
```

This then also means the logic of initially parsing those values can be removed from the entity factory entirely.

---

Additionally, #182 should be considered at the same time as doing this:

> <small>@FasterSpeeding</small>
> # Summary
> The idea is to possibly avoid discord from breaking older versions of the lib when they instantaneously release new enum values with zero warning by trying to cast the value to the enum and falling back to using the raw value rather than letting the value error propagate leading to the event being dropped as this will effect stuff like cache reliability and may lead to events being dropped over arguably insignificant values.
> 
> # Problem
> Discord doesn't know how versioning work.
> 
> # Ideal implementation
> enum fields (excluding int flags as these don't use range check validation) will be a union of the enum or the raw value we get from discord (either string or integer) and will fall back to the raw value if they couldn't be casted.
> 
> # Checklist
> [x] I have searched the issue tracker and have made sure it's not a duplicate.
> If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
Since we return the raw value if we fail to cast it, this:
```py
        if not isinstance(self._my_permissions, permissions_.Permissions):
            # This is unbound, we can convert it.
            self._my_permissions = permissions_.Permissions(self._my_permissions)
        return self._my_permissions
```
will not work really well since if we fail to cast it, the next call it will try to do it again. Imo, since the enum is much faster now, we dont really need to do this anymore. @nekokatt

**Comment by nekokatt** [comment]
@davfsa int flags work differently anyway and make pseudo members for values that do not exist.

```py
>>> import enum
>>>
>>> class Foo(enum.IntFlag):
...   a = 1
...   b = 2
...   c = 4
...
>>> Foo(8)
<Foo.8: 8>
```

**Comment by nekokatt** [comment]
For now I don't see this being overly necessary, so will close.
