### ISSUE TITLE
Consider removing the delete guild integration endpoint

### ISSUE THREAD

**Issue by FasterSpeeding** [nekokatt/hikari#210]
### Summary
According to the response https://github.com/discord/discord-api-docs/pull/2087#issuecomment-695869387 it seems that the delete guild integration endpoint has now become a glorified leave guild endpoint but with extra steps and unless discord does a u-turn on these changes this endpoint will just uselessly dupe the leave guild endpoint for bots.

### Problem
Discord doesn't care for how versioning works.

### Ideal implementation
The lack of an implementation for the endpoint.

### Checklist

- [ x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by FasterSpeeding** [comment]
Any word on this?

**Comment by davfsa** [comment]
I would say we should keep it till Discord decide to close it down

**Comment by nekokatt** [comment]
Im happy to remove it, I just only have one pair of hands right now.

**Comment by FasterSpeeding** [comment]
> I would say we should keep it till Discord decide to close it down

even though it's just duplicating leave guild?

**Comment by nekokatt** [comment]
or not i guess.

**Comment by FasterSpeeding** [comment]
> or not i guess.

accidentally pressed "close with comment"*

**Comment by nekokatt** [comment]
ah.

**Comment by davfsa** [comment]
Closed by #243
