### ISSUE TITLE
Stop using enums for non discrete values

### ISSUE THREAD

**Issue by nekokatt** [nekokatt/hikari#212]
This relates to #182, which is partially touched by #208.

We currently use enum types to represent constants. This is not ideal since Discord are... let's say not very consistent... at documenting what their API produces. They will add new fields and values without warning. This defeats the purpose of using an enum type to represent these in a way that is typesafe.

Instead, I propose we make a mechanism to handle this in a similar way. 

One idea I have had is the idea being we create a class via a metaclass we define that gets called with a string value. It can then either return an existing value if cached (store values in a dict, I guess, since primitiveish types cant be weakreffed nicely), or return the value it is called with. This would be efficient in terms of memory since stuff like strings could be interned to prevent making multiple copies of the same string in memory, possibly.

We may have to define this differently for ints and strings, since ints get interned differently (automatically for the first few thousand integers around zero), whereas strings need explicit sys.intern-ing for that to work.

If this is not MyPy compatible, we can always fall back to instead having a non-instantiating class that simply acts as a namespace to hold common values in.

This would not need to apply to Flag enum types like Intents and Permissions which already behave like this.

Another possibility is using the Flag type for values like the GuildFeature type in some cases, and latebinding it somehow. This would require the hikari.utilities.flags module to be changed to work with all flag types, not just IntFlag; use of enums is slower we need to remember, and unlike an int flag, there is the complexity of storing non-late-bound values in a list until we convert them.

If anyone has any feedback, feel free to pop a comment. I am just tossing ideas around here.

**Comment by davfsa** [comment]
I think this is closed by #214 since we now return raw values if we fail to find them in the enum. @nekokatt
