### ISSUE TITLE
Invalid codeblock in documentation

### ISSUE THREAD

**Issue by MonAaraj** [nekokatt/hikari#254]
### Steps to reproduce

1. Open https://nekokatt.github.io/hikari/hikari/impl/bot.html#hikari.impl.bot.BotApp.
2. Scroll down until the title which says `We want to make gateway logs output as DEBUG, and TRACE for all ratelimit content.`
3. Look right above.

### Expected Result
Find a valid codeblock 

### Actual Result
The codeblock seems to be invalid

### Further info
![Image of incomplete code block](https://cdn.discordapp.com/attachments/700378161526997003/761071932405710858/Screenshot_20201001-064751.jpg)

### Checklist

- [x] I have made sure to remove ANY sensitive information (bot token, passwords,
      credentials, personal details, etc).
- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by nekokatt** [comment]
cool, nice spot.

**Comment by davfsa** [comment]
This was fixed by 0016cfe2837d6e24e2d4465e69c83bb9aeb3c28e, next release should fix it. Thanks for pointing out tho :)
