### ISSUE TITLE
Add travis ci step to build pages

### ISSUE THREAD

**Issue by nekokatt** [nekokatt/hikari#257]
I'd like to move the travis CI stuff for deploying pages into its own stage and job and provide a mechanism to allow me to build them manually from `master` without having to make a release if I don't want to.

**Comment by davfsa** [comment]
Tbh, I don't think this might be a really good idea since we might have added some new features to `master` that are not in the pypi version that the documentation is built for, which might cause confusion on users that try to use some feature that is not there
