### ISSUE TITLE
Editing a role with the default permission value resets it to 0

### ISSUE THREAD

**Issue by YodaPY** [nekokatt/hikari#258]
### Steps to reproduce
1. Edit a role
2. Don't pass in any permission
3. See what happens

### Expected Result
It should edit the role with the default permission value

### Actual Result
It edits the role with permission value 0

### System info
hikari 2.0.0.dev85

### Checklist

- [x] I have made sure to remove ANY sensitive information (bot token, passwords,
      credentials, personal details, etc).
- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
I am unable to reproduce this. Could you please provide some sample code?
