### ISSUE TITLE
Cython

### ISSUE THREAD

**Issue by davfsa** [nekokatt/hikari#40]
Hopefully with the release of Cython 3 at some point, and https://github.com/cython/cython/pull/3691 hopefully being merged soon (thus giving support for the := operator), we should be able to start producing Cythonized artifacts for x86.

I believe the main issues before when we tried this were around:

- `from __future__ import annotations` was not supported. I know this is now supported.
- `Generic[T]` did not work properly. I am pretty sure this works now.
- `:=` was not supported (see the above PR).

This should give a nice performance boost where users choose to opt into the experimental accelerated builds :) (Cython usually gives at least 10 times speed increase over pure python from experience).

**Comment by nekokatt** [comment]
Currently this is still blocked on:
- https://github.com/cython/cython/issues/3794 (unable to subclass types in typing module)
- https://github.com/cython/cython/pull/3691 (implementing walrus operator)

Until then, I guess we will need to look at using something else to optimise this (i.e. pure C, C++, Rust)
