### ISSUE TITLE
Add missing documentation to REST 

### ISSUE THREAD

**Issue by davfsa** [nekokatt/hikari#42]
hikari.api.rest.RESTClient is missing a LOT of documentation still, and should be completed.

**Comment by nekokatt** [comment]
Closed by 1c65d27 in #114

**Comment by davfsa** [comment]
Still not closed, there is some more documentation to go

**Comment by nekokatt** [comment]
@davfsa is this complete?

**Comment by davfsa** [comment]
> is this complete?

Still some more docs to go, havent had time nor motivation to do so, will try to get it done as soon as I can
