### ISSUE TITLE
Cache optimisations and refinements

### ISSUE THREAD

**Issue by davfsa** [nekokatt/hikari#43]
The following discussion from !47 should be addressed:

- [ ] @nekokatt started a [discussion](https://gitlab.com/nekokatt/hikari/-/merge_requests/47#note_389850577):  (+3 comments)

    > Any time frame on remaining time before this is ready roughly?
    > 
    > What else is there to do?

    @FasterSpeeding 

    > The cache probably still has bugs and it isn't complete for sure but there's nowhere where it'd obviously raise a ton of errors when enabled (i.e a raise NotImplementedError or missing) so it should be mergable if those other threads are fine
    >
    > As far as stuff that needs to be done but I'm saving for another pr goes, we need performance improvements, intent awareness/features, test coverage (Inc a double check of how it handles hard refs), some small-consistency changes, configurability, statistics methods (e.g get count and maybe get guild ids for specific entity 
    > pool) and consilidation around how the cache is handled by the event listeners (I.e do we nuke it on a new session) off the top of my head.

**Comment by nekokatt** [comment]
@FasterSpeeding closing as no response.
